import {useEffect,useState} from 'react'
import {getConfig,getDecisions,getReady,getSamples,ingest} from './api/client'
import {AppHeader} from './components/AppHeader';import {JsonInput} from './components/JsonInput';import {EmailPreviewTable} from './components/EmailPreviewTable';import {RoutingProgress} from './components/RoutingProgress';import {ProcessingSummary} from './components/ProcessingSummary';import {DecisionTable} from './components/DecisionTable';import {ChatPanel} from './components/ChatPanel';import {ErrorPanel} from './components/ErrorPanel'
import type {Config,Decision,Email,IngestResult} from './types'
import {chunkEmails,validateEmails} from './features/input/validation'
import './styles.css'
import './mobile.css'

export default function App(){const[config,setConfig]=useState<Config|null>(null);const[status,setStatus]=useState('waking');const[text,setText]=useState('');const[emails,setEmails]=useState<Email[]>([]);const[error,setError]=useState('');const[routing,setRouting]=useState(false);const[progress,setProgress]=useState([0,0]);const[results,setResults]=useState<IngestResult[]>([]);const[decisions,setDecisions]=useState<Decision[]>([]);const[batch,setBatch]=useState<string|null>(null)
useEffect(()=>{let stopped=false;(async()=>{try{const c=await getConfig();if(stopped)return;setConfig(c);for(let i=0;i<12;i++){try{await getReady();setStatus('ready');return}catch{setStatus('waking');await new Promise(r=>setTimeout(r,2500))}}setStatus('offline')}catch(e){setStatus('offline');setError(String(e))}})();return()=>{stopped=true}},[])
function parse(){try{setEmails(validateEmails(JSON.parse(text)));setError('');setResults([]);setDecisions([])}catch(e){setError(e instanceof Error?e.message:String(e));setEmails([])}}
async function samples(){try{const r=await getSamples();setText(JSON.stringify(r.emails,null,2));setEmails(r.emails);setError('');setResults([]);setDecisions([])}catch(e){setError(e instanceof Error?e.message:String(e))}}
async function route(){if(!config||!emails.length)return;const id=crypto.randomUUID();const chunks=chunkEmails(emails,config.max_ingest_emails);setRouting(true);setProgress([0,chunks.length]);setResults([]);setError('');try{const completed:IngestResult[]=[];for(let i=0;i<chunks.length;i++){completed.push(await ingest(config.candidate_id,id,chunks[i]));setResults([...completed]);setProgress([i+1,chunks.length])}setBatch(id);setDecisions((await getDecisions(id)).items)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRouting(false)}}
return <main><AppHeader config={config} status={status}/><JsonInput value={text} onChange={setText} onParse={parse} onSample={samples} error=""/><ErrorPanel message={error}/><EmailPreviewTable emails={emails}/>{emails.length>0&&<RoutingProgress done={progress[0]} total={progress[1]} routing={routing} ready={status==='ready'} onRoute={route}/>}<ProcessingSummary results={results}/><DecisionTable items={decisions}/>{config&&<ChatPanel candidate={config.candidate_id} batch={batch}/>}<footer>Read-only analytics · one persistent task per thread · evidence over guesswork</footer></main>}
